---
---
title: "Comparison of Air pollution exposure models - RAQDPS-FW and CanOSSEM"
output: html_document
editor: 
  markdown: 
    wrap: 72
---

```{r setup, message = FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(lubridate)
library(stringr)
library(scales)
library(ggthemes)
library(heemod)
library(bcmaps)
require(sf)
```

```{r}
pm_canossem <- read.csv("./data/canossem_mo_hsda_2012_2022.csv")
pm_future0 <- read.csv("./data/future_pm25_0_2023_2036.csv")
pm_future25 <- read.csv("./data/future_pm25_25_2023_2036.csv")
pm_future50 <- read.csv("./data/future_pm25_50_2023_2036.csv")

pm_future0a <- readRDS("./data/future_pm25_5yr_0_2023_2036.rds")
pm_future25a <- readRDS("./data/future_pm25_5yr_25_2023_2036.rds")
pm_future50a <- readRDS("./data/future_pm25_5yr_50_2023_2036.rds")

raqdps <- read.csv("./data/projections/raqdps_mo_hsda_2012_2023.csv")
raqdpsfw <- read.csv("./data/projections/raqdpsfw_mo_hsda_2012_2023.csv")
gemmach <- read.csv("./data/projections/gemmach_2019_2036.csv")

raqdps_raqdpsfw_combined <- readRDS("./data/backups/average_monthly_wildfire_smoke_HSDA_2018_2023.rds")
raqdps_raqdpsfw_combineda <- readRDS("./data/backups/average_5yr_monthly_wildfire_smoke_HSDA_2018_2023.rds")


glimpse(raqdps)
glimpse(raqdpsfw)

glimpse(raqdps_raqdpsfw_combined)
glimpse(pm_future0a)
```
# Cleaning air pollution data.
```{r}
bc_hsda <- st_drop_geometry(bc_hsda)

  
pm_h <- pm_canossem %>%
  mutate(
    HLTH_SERVICE_DLVR_AREA_CODE = as.integer(HLTH_SERVICE_DLVR_AREA_CODE),
    date = as.Date(date, format = "%Y-%m-%d"),  # Convert date column to Date format
    pm25 = monthly_smoke  # Rename monthly_smoke to pm
  ) %>%
  select(-monthly_smoke) %>%
  left_join(bc_hsda %>%
              mutate(HLTH_SERVICE_DLVR_AREA_CODE = as.integer(HLTH_SERVICE_DLVR_AREA_CODE)), by = "HLTH_SERVICE_DLVR_AREA_CODE") %>%
  select(HLTH_SERVICE_DLVR_AREA_NAME, year, month, date, pm25)

pm_f0 <- pm_future0 %>%
   mutate(
    date = as.Date(date, format = "%Y-%m-%d"),  # Convert date column to Date format
    pm25 = total_pm25  # Rename monthly_smoke to pm
  ) %>%
    select(HLTH_SERVICE_DLVR_AREA_NAME, year, month, date, pm25, background_pm25, wildfire_pm25)


pm_f25 <- pm_future25 %>%
   mutate(
    date = as.Date(date, format = "%Y-%m-%d"),  # Convert date column to Date format
    pm25 = total_pm25  # Rename monthly_smoke to pm
  ) %>%
    select(HLTH_SERVICE_DLVR_AREA_NAME, year, month, date, pm25, background_pm25, wildfire_pm25)

pm_f50 <- pm_future50 %>%
     mutate(
    date = as.Date(date, format = "%Y-%m-%d"),  # Convert date column to Date format
    pm25 = total_pm25  # Rename monthly_smoke to pm
  ) %>%
    select(HLTH_SERVICE_DLVR_AREA_NAME, year, month, date, pm25, background_pm25, wildfire_pm25)

# Using 5-year averages

pm_f0a <- pm_future0a %>%
   mutate(
    date = as.Date(date, format = "%Y-%m-%d"),  # Convert date column to Date format
    pm25 = total_pm25  # Rename monthly_smoke to pm
  ) %>%
    select(HLTH_SERVICE_DLVR_AREA_NAME, year, month, date, pm25, background_pm25, wildfire_pm25)


pm_f25a <- pm_future25a %>%
   mutate(
    date = as.Date(date, format = "%Y-%m-%d"),  # Convert date column to Date format
    pm25 = total_pm25  # Rename monthly_smoke to pm
  ) %>%
    select(HLTH_SERVICE_DLVR_AREA_NAME, year, month, date, pm25, background_pm25, wildfire_pm25)

pm_f50a <- pm_future50a %>%
     mutate(
    date = as.Date(date, format = "%Y-%m-%d"),  # Convert date column to Date format
    pm25 = total_pm25  # Rename monthly_smoke to pm
  ) %>%
    select(HLTH_SERVICE_DLVR_AREA_NAME, year, month, date, pm25, background_pm25, wildfire_pm25)

glimpse(raqdps_raqdpsfw_combined)
pm_raqdpsfw_raqdps <- raqdps_raqdpsfw_combined %>%
     mutate(
    year = year(date),
    month = month(date),
    date = as.Date(date, format = "%Y-%m-%d"),  # Convert date column to Date format
    pm25 = wildfire_pm25  # Rename monthly_smoke to pm
  ) %>%
    select(HLTH_SERVICE_DLVR_AREA_NAME, year, month, date, pm25, average_mo_raqdpsfw, average_mo_raqdps)

pm_raqdpsfw_raqdpsa <- raqdps_raqdpsfw_combineda %>%
     mutate(
    year = year(date),
    month = month(date),
    date = as.Date(date, format = "%Y-%m-%d"),  # Convert date column to Date format
    pm25 = wildfire_pm25  # Rename monthly_smoke to pm
  ) %>%
    select(HLTH_SERVICE_DLVR_AREA_NAME, year, month, date, pm25, average_mo_raqdpsfw, average_mo_raqdps)
glimpse(pm_raqdpsfw_raqdpsa)

saveRDS(pm_raqdpsfw_raqdps, "pm25_historical_raqdps_raqdpsfw_2018_2022_cleaned.rds")
saveRDS(pm_raqdpsfw_raqdpsa, "pm25_historical_raqdps_raqdpsfw_5yr_avg_2018_2022_cleaned.rds")

write.csv(pm_h, "pm25_historical_canossem_2012_2022_cleaned.csv")
write.csv(pm_f0, "pm25_future_0_2023_2036_cleaned.csv")
write.csv(pm_f25, "pm25_future_25_2023_2036_cleaned.csv")
write.csv(pm_f50, "pm25_future_50_2023_2036_cleaned.csv")

saveRDS(pm_f0a, "pm25_future_0_5yr_2023_2036_cleaned.rds")
saveRDS(pm_f25a, "pm25_future_25_5yr_2023_2036_cleaned.rds")
saveRDS(pm_f50a, "pm25_future_50_5yr_2023_2036_cleaned.rds")

glimpse(pm_h)
glimpse(pm_f0)
glimpse(pm_f25)
glimpse(pm_f50)

pm_h <- pm_h %>% mutate(scenario = "historical")
pm_f0 <- pm_f0 %>% mutate(scenario = "projection_0")
pm_f25 <- pm_f25 %>% mutate(scenario = "projection_25")
pm_f50 <- pm_f50 %>% mutate(scenario = "projection_50")

pm_h <- pm_h %>% mutate(scenario = "historical")
pm_f0a <- pm_f0a %>% mutate(scenario = "projection_0")
pm_f25a <- pm_f25a %>% mutate(scenario = "projection_25")
pm_f50a <- pm_f50a %>% mutate(scenario = "projection_50")
pm_rr <- pm_raqdpsfw_raqdps %>% mutate(scenario = "raqdpsfw")


pm_combineda <- bind_rows(pm_h, pm_f0a, pm_f25a, pm_f50a, pm_rr)
glimpse(pm_combineda)
```

# Plotting combined data
```{r}
haLineMo_A <- function(data, y, title){
  ggplot(data) +
    geom_line(aes(x = date, y = !!enquo(y)), linewidth = 0.5) +
    scale_x_date(breaks = seq(as.Date("2012-01-01"), as.Date("2023-01-01"), by = "2 years"),
                 date_minor_breaks = "1 year",
                 date_labels = "%Y") +
    coord_cartesian(ylim = c(0, 100)) +
    theme_few(base_size = 8) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1),
      legend.position = "right",
      panel.grid.minor = element_blank(),      # Remove minor grid lines
      panel.grid.major = element_blank(),      # Remove major grid lines
      axis.ticks = element_line(color = "black"),
      axis.ticks.length = unit(0.15, "cm")
    ) +
    facet_wrap(~ HLTH_SERVICE_DLVR_AREA_NAME) +
    labs(title = title, x = "", y = "µg/m³")
}

plot_raqdpsfw_5yr_avg <- haLineMo_A(pm_rr, pm25, "Wildfire PM2.5, RAQDPS-FW - RAQDPS (2018-2022)")
ggsave("wildfire_pm25_raqdpsfw_raqdps_5yr_avg_2018_2022.png", plot_raqdpsfw_5yr_avg, width = 8, height = 6)

haLineMo_B <- function(data, y, title){
  ggplot(data) +
    geom_line(aes(x = date, y = !!enquo(y)), linewidth = 0.5) +
    scale_x_date(breaks = seq(as.Date("2023-01-01"), as.Date("2036-01-01"), by = "2 years"),
                 date_minor_breaks = "1 year",
                 date_labels = "%Y") +
    coord_cartesian(ylim = c(0, 100)) +
    theme_few(base_size = 8) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1),
      legend.position = "right",
      panel.grid.minor = element_blank(),      # Remove minor grid lines
      panel.grid.major = element_blank(),      # Remove major grid lines
      axis.ticks = element_line(color = "black"),
      axis.ticks.length = unit(0.15, "cm")
    ) +
    facet_wrap(~ HLTH_SERVICE_DLVR_AREA_NAME) +
    labs(title = title, x = "", y = "µg/m³")
    }
    
plot_pm25_h <- haLineMo_A(pm_h, pm25, "CanOSSEM PM2.5, 2012-2022")
ggsave(filename = "plot_pm25_CanOSSEM.png", plot = plot_pm25_h, width = 8, height = 6)


haLineMo_B(pm_f0, pm25, "GEM-MACH projections PM2.5, 2023-2036, 0% increase in wildfires from 2023-2100")
haLineMo_B(pm_f25, pm25, "GEM-MACH projections PM2.5, 2023-2036, 25% increase in wildfires from 2023-2100")
haLineMo_B(pm_f50, pm25, "GEM-MACH projections PM2.5, 2023-2036, 50% increase in wildfires from 2023-2100")

plot_pmf0a <- haLineMo_B(pm_f0a, pm25, "GEM-MACH projections PM2.5, 5-yr historical average, 2023-2036, 0% increase in wildfires from 2023-2100")
plot_pmf25a <- haLineMo_B(pm_f25a, pm25, "GEM-MACH projections PM2.5, 5-yr historical average, 2023-2036, 25% increase in wildfires from 2023-2100")
plot_pmf50a <- haLineMo_B(pm_f50a, pm25, "GEM-MACH projections PM2.5, 5-yr historical average, 2023-2036, 50% increase in wildfires from 2023-2100")

ggsave("line_pm25_5yr_0.png", plot = plot_pmf0a, width = 8, height = 6)
ggsave("line_pm25_5yr_25.png", plot = plot_pmf25a, width = 8, height = 6)
ggsave("line_pm25_5yr_50.png", plot = plot_pmf50a, width = 8, height = 6)

glimpse(pm_combined)

haLineMo_project1 <- ggplot(pm_combined) +
    geom_line(aes(x = date, y = pm25, colour = scenario), linewidth = 0.25, alpha = 0.7, position = position_jitter(width = 0.25)) +
    scale_x_date(breaks = seq(as.Date("2012-01-01"), as.Date("2037-01-01"), by = "5 years"),
                 date_minor_breaks = "1 year",
                 date_labels = "%Y") +
    coord_cartesian(ylim = c(0, 120)) +
    theme_few(base_size = 8) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1),
      legend.position = "right",
      panel.grid.minor = element_blank(),      # Remove minor grid lines
      panel.grid.major = element_blank(),      # Remove major grid lines
      axis.ticks = element_line(color = "black"),
      axis.ticks.length = unit(0.15, "cm")
    ) +
    facet_wrap(~ HLTH_SERVICE_DLVR_AREA_NAME) +
    labs(title = "Historical and Projected PM2.5 Levels", x = "", y = "µg/m³")

haLineMo_project1

haLineMo_project2 <- ggplot(pm_combineda) +
    geom_line(aes(x = date, y = pm25, colour = scenario), linewidth = 0.25, alpha = 0.7, position = position_jitter(width = 0.25)) +
    scale_x_date(breaks = seq(as.Date("2012-01-01"), as.Date("2037-01-01"), by = "5 years"),
                 date_minor_breaks = "1 year",
                 date_labels = "%Y") +
    coord_cartesian(ylim = c(0, 120)) +
    theme_few(base_size = 8) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1),
      legend.position = "right",
      panel.grid.minor = element_blank(),      # Remove minor grid lines
      panel.grid.major = element_blank(),      # Remove major grid lines
      axis.ticks = element_line(color = "black"),
      axis.ticks.length = unit(0.15, "cm")
    ) +
    facet_wrap(~ HLTH_SERVICE_DLVR_AREA_NAME) +
    labs(title = "Historical and Projected PM2.5 Levels", x = "", y = "µg/m³")

haLineMo_project2

pm_h_f0 <- pm_combined %>%
  filter(scenario %in% c("historical", "projection_0", "raqdpsfw"))
pm_h_f25 <- pm_combined %>%
  filter(scenario %in% c("historical", "projection_25"))
pm_h_f50 <- pm_combined %>%
  filter(scenario %in% c("historical", "projection_50"))

halineMo_C <- function(data, pm25, scenario, title){
    ggplot(data) +
    geom_line(aes(x = date, y = pm25, colour = scenario), linewidth = 0.25, alpha = 0.7, position = position_jitter(width = 0.25)) +
    scale_x_date(breaks = seq(as.Date("2012-01-01"), as.Date("2037-01-01"), by = "5 years"),
                 date_minor_breaks = "1 year",
                 date_labels = "%Y") +
    scale_color_manual(values = c("historical" = "black", "raqdpsfw" = "darkblue","projection_0" = "violetred2", "projection_25" = "violetred3", "projection_50" = "violetred4")) +
    coord_cartesian(ylim = c(0, 100)) +
    theme_few(base_size = 8) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1),
      legend.position = "right",
      panel.grid.minor = element_blank(),      # Remove minor grid lines
      panel.grid.major = element_blank(),      # Remove major grid lines
      axis.ticks = element_line(color = "black"),
      axis.ticks.length = unit(0.15, "cm")
    ) +
    facet_wrap(~ HLTH_SERVICE_DLVR_AREA_NAME) +
    labs(title = title, x = "", y = "µg/m³")
}


plot_pm25_hf0 <- halineMo_C(pm_h_f0, pm25, scenario, "Historical and projected total PM2.5, assuming 0% increase in wildfire PM2.5 from 2023-2100")

plot_pm25_hf25 <- halineMo_C(pm_h_f25, pm25, scenario, "Historical and projected total PM2.5, assuming 25% increase in wildfire PM2.5 from 2023-2100")

plot_pm25_hf50 <- halineMo_C(pm_h_f50, pm25, scenario, "Historical and projected total PM2.5, assuming 50% increase in wildfire PM2.5 from 2023-2100")

ggsave(filename = "pm25_historical_projection0.png", plot = plot_pm25_hf0, width = 8, height = 6)

ggsave(filename = "pm25_historical_projection25.png", plot = plot_pm25_hf25, width = 8, height = 6)

ggsave(filename = "pm25_historical_projection50.png", plot = plot_pm25_hf50, width = 8, height = 6)


pm_h_f0a <- pm_combineda %>%
  filter(scenario %in% c("historical", "projection_0", "raqdpsfw"))
pm_h_f25a <- pm_combineda %>%
  filter(scenario %in% c("historical", "projection_25", "raqdpsfw"))
pm_h_f50a <- pm_combineda %>%
  filter(scenario %in% c("historical", "projection_50", "raqdpsfw"))

plot_pm25_hf0a <- halineMo_C(pm_h_f0a, pm25, scenario, "Historical and projected total PM2.5, assuming 0% increase in wildfire PM2.5 from 2023-2100")

plot_pm25_hf25a <- halineMo_C(pm_h_f25a, pm25, scenario, "Historical and projected total PM2.5, assuming 25% increase in wildfire PM2.5 from 2023-2100")

plot_pm25_hf50a <- halineMo_C(pm_h_f50a, pm25, scenario, "Historical and projected total PM2.5, assuming 50% increase in wildfire PM2.5 from 2023-2100")

ggsave(filename = "pm25_historical_5yr_projection0.png", plot = plot_pm25_hf0a, width = 8, height = 6)

ggsave(filename = "pm25_historical_5yr_projection25.png", plot = plot_pm25_hf25a, width = 8, height = 6)

ggsave(filename = "pm25_historical_5yr_projection50.png", plot = plot_pm25_hf50a, width = 8, height = 6)
```

# Functions for later
```{r}
haLineMo <- function (data, title) {
    ggplot(data) +
    geom_line(aes(x = date, y = background_pm25, colour = HLTH_SERVICE_DLVR_AREA_NAME), linewidth = 0.5) +
    scale_x_date(date_labels = "%m-%Y", date_breaks = "12 month") +
    theme_few(base_size = 8) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1),
      legend.position = "none"
    ) +
    facet_wrap(~ HLTH_SERVICE_DLVR_AREA_NAME) +
    labs(title = title,
    x = "",
    y = "µg/m³")
}


haLineMo2 <- function (data, title) {
    ggplot(data) +
    geom_line(aes(x = date, y = wildfire_pm25, colour = HLTH_SERVICE_DLVR_AREA_NAME), linewidth = 0.5) +
    scale_x_date(date_labels = "%m-%Y", date_breaks = "12 month") +
    theme_few(base_size = 8) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1),
      legend.position = "none"
    ) +
    facet_wrap(~ HLTH_SERVICE_DLVR_AREA_NAME) +
    labs(title = title,
    x = "",
    y = "µg/m³")
}

haLineMo_project <- function (data, title, sub) {
    ggplot(data) +
    geom_line(aes(x = date, y = !!enquo(sub), colour = HLTH_SERVICE_DLVR_AREA_NAME), linewidth = 0.5) +
    scale_x_date(breaks = seq(as.Date("2020-01-01"), as.Date("2100-01-01"), by = "5 years"),
                 date_minor_breaks = "1 year",
                 date_labels = "%Y") +
    theme_few(base_size = 8) +
    theme(
     axis.text.x = element_text(angle = 90, hjust = 1),
      legend.position = "none",
      panel.grid.minor = element_blank(),      # Remove minor grid lines
      panel.grid.major = element_blank(), # Keep major grid lines if desired
      axis.ticks = element_line(color = "black"), # Enable ticks
      axis.ticks.length = unit(0.15, "cm")     # Adjust tick length if needed
    ) +
    facet_wrap(~ HLTH_SERVICE_DLVR_AREA_NAME) +
    labs(title = title,
    ylim(0, 100),
    x = "",
    y = "µg/m³")
}
```
# Some cleaning and prep
```{r}
combined_raq <- raqdps %>%
  select(c("average_mo", "date", "HLTH_SERVICE_DLVR_AREA_NAME")) %>%
  inner_join(raqdpsfw, by = c("date", "HLTH_SERVICE_DLVR_AREA_NAME"), suffix = c("_raqdps", "_raqdpsfw"))

wildfire_smoke <- combined_raq %>%
  mutate(sanity = average_mo_raqdpsfw >= average_mo_raqdps,
         wildfire_pm25 = average_mo_raqdpsfw - average_mo_raqdps) 

summary(wildfire_smoke$wildfire_pm25)  
wildfire_smoke %>% glimpse()
summary(wildfire_smoke$sanity) 


# Cancelling the negative wildfire contributions
wildfire_smoke <- wildfire_smoke %>% 
  select(HLTH_SERVICE_DLVR_AREA_NAME, date, wildfire_pm25, average_mo_raqdpsfw, average_mo_raqdps) %>%
  mutate(wildfire_pm25 = if_else(wildfire_pm25<0, 0, wildfire_pm25)) %>%
  mutate(wildfire_pm25 =replace_na(wildfire_pm25, 0)) %>%
  mutate(date = ymd(date)) %>%
  arrange(HLTH_SERVICE_DLVR_AREA_NAME, date)

summary(wildfire_smoke$wildfire_pm25)  
wildfire_smoke %>% glimpse()
summary(wildfire_smoke$sanity) 

haLineMo2(wildfire_smoke, "Wildfire contribution to total PM2.5, derived from RAQDPS-FW (total PM2.5 with wildfire smoke) - RAQDPS (total PM2.5 without wildfire smoke)")

write.csv(wildfire_smoke, "average_monthly_wildfire_smoke_HSDA_2018_2023.csv")
```

# Writing files
```{r}
write.csv(pm_combined, "pm25_historical_future_2012_2036_all.csv")
write.csv(pm_h_f0, "pm25_historical_future_2012_2036_0.csv")
write.csv(pm_h_f25, "pm25_historical_future_2012_2036_25.csv")
write.csv(pm_h_f50, "pm25_historical_future_2012_2036_50.csv")

saveRDS(pm_combined,  "pm25_historical_future_2012_2036_all.rds")
saveRDS(pm_h_f0, "pm25_historical_future_2012_2036_0.rds")
saveRDS(pm_h_f25, "pm25_historical_future_2012_2036_25.rds")
saveRDS(pm_h_f50, "pm25_historical_future_2012_2036_50.rds")

saveRDS(pm_combineda,  "pm25_historical_future_5yr_2012_2036_all.rds")
saveRDS(pm_h_f0a, "pm25_historical_future_5yr_2012_2036_0.rds")
saveRDS(pm_h_f25a, "pm25_historical_future_5yr_2012_2036_25.rds")
saveRDS(pm_h_f50a, "pm25_historical_future_5yr_2012_2036_50.rds")
```